const Most_Popular_EpisodesAPI = [
    {
        title: "The Power of Faith",
        date: "07-11-2025",
        description: "Molana Zameer beautifully explains how strong faith brings peace, purpose, and success in both worldly and spiritual life.",
        img: "https://ik.imagekit.io/hmdcfponi/Bazam%20Zameer/News/Bazam_Zameer/9?updatedAt=1762764258645",
    }, {
        title: "Respecting Parents A Path to Jannah",
        date: "07-11-2025",
        description: "A heart-touching episode highlighting the importance of serving and respecting parents as a key to Paradise.",
        img: "https://ik.imagekit.io/hmdcfponi/Bazam%20Zameer/News/Bazam_Zameer/9?updatedAt=1762764258645",
    }, {
        title: "The Blessings of Gratitude",
        date: "07-11-2025",
        description: "Learn how gratitude strengthens your relationship with Allah and fills your life with blessings and inner happiness.",
        img: "https://ik.imagekit.io/hmdcfponi/Bazam%20Zameer/News/Bazam_Zameer/9?updatedAt=1762764258645",
    }, {
        title: "Youth and Modern Challenges",
        date: "07-11-2025",
        description: "Molana Zameer discusses how today’s youth can balance deen and dunya while facing modern world distractions and struggles.",
        img: "https://ik.imagekit.io/hmdcfponi/Bazam%20Zameer/News/Bazam_Zameer/9?updatedAt=1762764258645",
    }, {
        title: "Secrets of a Peaceful Heart",
        date: "07-11-2025",
        description: "This episode shares the Islamic ways to overcome stress, anxiety, and find true inner peace through remembrance of Allah.",
        img: "https://ik.imagekit.io/hmdcfponi/Bazam%20Zameer/News/Bazam_Zameer/9?updatedAt=1762764258645",
    }, {
        title: "Quran The Light of Guidance",
        date: "07-11-2025",
        description: "An inspiring talk about how the Holy Quran guides every aspect of life and brings clarity, wisdom, and faith to believers.",
        img: "https://ik.imagekit.io/hmdcfponi/Bazam%20Zameer/News/Bazam_Zameer/9?updatedAt=1762764258645",
    },
];
const Teamsection = [
    {
        img: "https://ik.imagekit.io/hmdcfponi/Team/t1?updatedAt=1763026213370",
        name: "M Ammaz Jahanzeb",
        desig: "Ameer, Molana Zameer Platform",
        paragraph: "Muhammad Ammaz Jahanzeb serves as the Ameer, Molana Zameer Platform of the Molana Zameer Platform, managing coordination and discipline with great dedication. His efforts and commitment form the foundation of the platform’s continuous growth and success.",
        face: "https://www.facebook.com/AmmazLife",
        insta: "https://www.instagram.com/ammazlife/",
        tiktok: "https://www.tiktok.com/@amaz3824",
    }, {
        img: "https://ik.imagekit.io/hmdcfponi/Team/t2?updatedAt=1763026237242",
        name: "Muhammad Rizwan",
        desig: "Head of IT Department",
        paragraph: "Muhammad Rizwan, the Head of the IT Department, drives the platform toward digital excellence through innovative technology. His creativity, technical expertise, and problem-solving mindset make him a valuable asset to the entire team.",
        face: "https://www.facebook.com/muhammad.rizwan.tajdin",
        insta: "https://www.instagram.com/ranarizwan7351/",
        tiktok: "https://www.tiktok.com/@ranarizwan7351",
    },
];
const BazamData = [
    {
        category: "2025",
        img: "https://ik.imagekit.io/hmdcfponi/BazamData/1?updatedAt=1768294242213",
        h1: "Inamullah",
        p: "Some quick example text to build on the...",
        Facebook: "https://www.facebook.com/share/p/19W5ebwaVS/",
        Instagram: "https://www.instagram.com/p/DQggGupjNBX/",
        Youtube: "https://youtu.be/b3c5E5cTsNI?si=ePADUs90JiXgxLLw",
        Whatsapp: "https://whatsapp.com/channel/0029Vb5lsO9G8l57GXZ9CU3L",
        TikTok: "https://www.tiktok.com/@molanazameer/video/7567682546658495764?is_from_webapp=1&sender_device=pc&web_id=7500289490197988865",
    }, {
        category: "2025",
        img: "https://ik.imagekit.io/hmdcfponi/BazamData/2?updatedAt=1768301114937",
        h1: "Ehtesham-ul-Haq",
        p: "Some quick example text to build on the...",
        Facebook: "https://www.facebook.com/share/p/1Bp1j577E7/",
        Instagram: "https://www.instagram.com/p/DQghcZ7jHUQ/",
        Youtube: "https://youtu.be/jDgnYLTT7rc?si=ckeNGLwn_vhq_CEg",
        Whatsapp: "https://whatsapp.com/channel/0029Vb5lsO9G8l57GXZ9CU3L",
        TikTok: "https://www.tiktok.com/@molanazameer/video/7567683525315497236?is_from_webapp=1&sender_device=pc&web_id=7500289490197988865",
    }, {
        category: "2025",
        img: "https://ik.imagekit.io/hmdcfponi/BazamData/3?updatedAt=1768301486041",
        h1: "Muhammad Saffron",
        p: "Some quick example text to build on the...",
        Facebook: "https://www.facebook.com/share/p/1Dmyt9Ve7L/",
        Instagram: "https://www.instagram.com/p/DQgkLF_jDex/",
        Youtube: "https://youtu.be/aG1tTPY4dAk?si=ex8ZVVgd8-HpOQQB",
        Whatsapp: "https://whatsapp.com/channel/0029Vb5lsO9G8l57GXZ9CU3L",
        TikTok: "https://www.tiktok.com/@molanazameer/video/7567687346821287189?is_from_webapp=1&sender_device=pc&web_id=7500289490197988865",
    }, {
        category: "2025",
        img: "https://ik.imagekit.io/hmdcfponi/BazamData/4?updatedAt=1768470983069",
        h1: "Hafiz M Sheeraz",
        p: "Some quick example text to build on the...",
        Facebook: "https://www.facebook.com/molanazameer2025",
        Instagram: "https://www.instagram.com/mola.nazameer/",
        Youtube: "https://youtu.be/YrKkB8nCghQ?si=MYa-XEbOXbaeazsG",
        Whatsapp: "https://whatsapp.com/channel/0029Vb5lsO9G8l57GXZ9CU3L",
        TikTok: "https://www.tiktok.com/@molanazameer",
    }, {
        category: "2025",
        img: "https://ik.imagekit.io/hmdcfponi/BazamData/5?updatedAt=1768472450279",
        h1: "Ibadur Rehman",
        p: "Some quick example text to build on the...",
        Facebook: "https://www.facebook.com/share/p/1AunCVjGbW/",
        Instagram: "https://www.instagram.com/p/DSjfil6CDKJ/",
        Youtube: "https://youtu.be/K7YnnfoGdZg?si=PuwUT89m0fspuveN",
        Whatsapp: "https://whatsapp.com/channel/0029Vb5lsO9G8l57GXZ9CU3L",
        TikTok: "https://www.tiktok.com/@molanazameer",
    }, {
        category: "2025",
        img: "https://ik.imagekit.io/hmdcfponi/BazamData/6?updatedAt=1768483097315",
        h1: "M Shahid Hazarvi",
        p: "Some quick example text to build on the...",
        Facebook: "https://www.facebook.com/share/p/16ekNy2t75/",
        Instagram: "https://www.instagram.com/p/DS1d3i_iGUt/",
        Youtube: "https://youtu.be/YztuYp5ItwA?si=DyI-okIdwSyv2QSB",
        Whatsapp: "https://whatsapp.com/channel/0029Vb5lsO9G8l57GXZ9CU3L",
        TikTok: "https://www.tiktok.com/@molanazameer",
    }, {
        category: "2025",
        img: "https://ik.imagekit.io/hmdcfponi/BazamData/7?updatedAt=1768483754285",
        h1: "Samiullah",
        p: "Some quick example text to build on the...",
        Facebook: "https://www.facebook.com/molanazameer2025",
        Instagram: "https://www.instagram.com/mola.nazameer/",
        Youtube: "https://youtu.be/Y7wvVx_dG5c?si=phj9mnZq0eDHhPF4",
        Whatsapp: "https://whatsapp.com/channel/0029Vb5lsO9G8l57GXZ9CU3L",
        TikTok: "https://www.tiktok.com/@molanazameer",
    }, {
        category: "2025",
        img: "https://ik.imagekit.io/hmdcfponi/BazamData/8?updatedAt=1768486087003",
        h1: "Ismatullah",
        p: "Some quick example text to build on the...",
        Facebook: "https://www.facebook.com/molanazameer2025",
        Instagram: "https://www.instagram.com/mola.nazameer/",
        Youtube: "https://youtu.be/YdBgN_cdyH0?si=RyLHitPCKZDHoYr4",
        Whatsapp: "https://whatsapp.com/channel/0029Vb5lsO9G8l57GXZ9CU3L",
        TikTok: "https://www.tiktok.com/@molanazameer",
    }, {
        category: "2025",
        img: "https://ik.imagekit.io/hmdcfponi/BazamData/9?updatedAt=1768488043778",
        h1: "Ismatullah",
        p: "Some quick example text to build on the...",
        Facebook: "https://www.facebook.com/molanazameer2025",
        Instagram: "https://www.instagram.com/mola.nazameer/",
        Youtube: "https://youtu.be/Q1NN_4Yw0T8?si=xceqQ9u_BAibM_9W",
        Whatsapp: "https://whatsapp.com/channel/0029Vb5lsO9G8l57GXZ9CU3L",
        TikTok: "https://www.tiktok.com/@molanazameer",
    }, {
        category: "2026",
        img: "https://ik.imagekit.io/hmdcfponi/Conferences/0?updatedAt=1768386681953",

    }, {
        category: "2027",
        img: "https://ik.imagekit.io/hmdcfponi/Conferences/0?updatedAt=1768386681953",
    },
];
export default Most_Popular_EpisodesAPI;
export { Teamsection, BazamData };

